### ISSUE TITLE
[DATA] mixture map generation

### ISSUE THREAD

**Issue by Haoban** [DY112/LSMI-dataset#2]
Hi DongYoung,

I met some problem when using the generated the mixture map from Nikon D810 dataset. Could you check the scene I put in following? It's a kinda weird illumination contour. The image is Place550_12, in Nikon dataset. I do have a different result both from rawpy and own prediction at the blueish color cast area.

![Place550_12](https://user-images.githubusercontent.com/37427359/166924780-20a83cf2-08d3-4bf0-8c7f-3b7e149fc355.png)
 
Thanks

**Comment by DY112** [comment]
Hi Haoban, I'll check about this as soon as possible.
It will take about a week I think.
Thanks.

**Comment by DY112** [comment]
Hi Haoban, I checked the scene and here's my answer.
As mentioned in my paper, our dataset's pixelwise mixture map was generated through "approximation".
We approximate the pixelwise mixture ratio as the ratio of green channel, and we found that this assumption did not hold for some scenes.
Moreover, we didn't consider the reflected indirect illumination in our image model, some scene may have erroneous result due to this reason.
In the near future we plan to provide a better "refined dataset" by examining these scenes and providing the corresponding indices.
We can't confirm the release date, but we are also planning to release new algorithm code for generating illumination-maps in other ways.
Thank you for your interest in our work.

**Comment by Haoban** [comment]
> Hi Haoban, I checked the scene and here's my answer. As mentioned in my paper, our dataset's pixelwise mixture map was generated through "approximation". We approximate the pixelwise mixture ratio as the ratio of green channel, and we found that this assumption did not hold for some scenes. Moreover, we didn't consider the reflected indirect illumination in our image model, some scene may have erroneous result due to this reason (very few). In the near future we plan to provide a better "refined dataset" by examining these erroneous scenes and providing the corresponding indices. We can't confirm the release date, but we are also planning to release new algorithm code for generating illumination-maps in other ways. Thank you for your interest in our work.

ok, thanks for you reply. I didn't get any reminding from github about this issue even if I open it every day, until today you closed this issue. That's a good news and looking forward your future work.
