### ISSUE TITLE
bug in preprocess_data.py

### ISSUE THREAD

**Issue by aamircs** [DY112/LSMI-dataset#4]
in preprocess data file all the obtained output image are black in color
it's not the white balanced image which we need for training the model

**Comment by DY112** [comment]
Hi, @aamircs, thank you for your interest about our work.
The result image files of preprocessing code are not the general image, but the RAW tiff image.
So the range of pixel value will be 1023~16383, which is the bit depth of the camera which was used to capture the scene.

**Comment by aamircs** [comment]
Thanks for your quick response but my issue
is that, when we run 2_preprocess_data.py a galaxy_512 folder is generated
in which there are 3 sub folder train,test,val. All the ground truth images
inside the folders ( For eg: Place1003_13_gt) are complete black..Also the
mask images are all black..Can you guide us about this issue ?

**Comment by DY112** [comment]
I mean, all that black images are not complete black(0) , but they have 0-1023 or 0-16383 RAW values.
Since they are saved as lossless tiff format, general image viewer can not represent them properly to display.
If you want to see the scene content, please refer `visualize.py` and visualization process in `1_make_mixture_map.py`.

However, the visualization process distorts the linear raw values and transforms them into sRGB format, so it is not suitable for use in experiments.

https://github.com/DY112/LSMI-dataset/blob/ade6a99556522ec91b3783c2a45a43549707c70f/1_make_mixture_map.py#L418
